version: '3.9'

services:
  # API Gateway
  gateway:
    image: api-gateway:latest
    container_name: api-gateway
    build: ./
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail 127.0.0.1:8080/ping || echo 1
      interval: 60s
      start_period: 20s
      timeout: 10s

